# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('assigned_device', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('identifier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('waste_type', models.CharField(max_length=20)),
                ('custom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gty_ccn_alert', models.BooleanField(default=False)),
                ('gty_email_alert', models.BooleanField(default=False)),
                ('gty_sms_alert', models.BooleanField(default=False)),
                ('ytr_ccn_alert', models.BooleanField(default=False)),
                ('ytr_email_alert', models.BooleanField(default=False)),
                ('ytr_sms_alert', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=20)),
                ('gy_thresh', models.IntegerField(max_length=2)),
                ('yr_thresh', models.IntegerField(max_length=2)),
                ('parent_user', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='smart_city_main.User'),
        ),
    ]
