# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('assigned_device', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('identifier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('battery_level', models.IntegerField(default=100)),
                ('fill_level', models.IntegerField(default=0)),
                ('device_type', models.CharField(max_length=20)),
                ('custom', models.CharField(max_length=255)),
                ('sensing_interval', models.IntegerField(default=15)),
                ('last_notification_date', models.DateTimeField(default=datetime.datetime(1999, 1, 1, 0, 0, 1))),
            ],
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elist_parent_user', models.CharField(max_length=50)),
                ('third_party_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=250)),
                ('alert_date', models.DateTimeField()),
                ('device_identifier', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='smart_city_main.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gty_web_alert', models.BooleanField(default=True)),
                ('gty_email_alert', models.BooleanField(default=False)),
                ('ytr_web_alert', models.BooleanField(default=True)),
                ('ytr_email_alert', models.BooleanField(default=False)),
                ('clean_basin_web_alert', models.BooleanField(default=True)),
                ('clean_basin_email_alert', models.BooleanField(default=False)),
                ('gps_update_web_alert', models.BooleanField(default=True)),
                ('gps_update_email_alert', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(blank=True, max_length=15)),
                ('language', models.CharField(max_length=20)),
                ('gy_thresh', models.IntegerField(default=30)),
                ('yr_thresh', models.IntegerField(default=60)),
                ('parent_user', models.CharField(max_length=50)),
                ('permission', models.CharField(default='User', max_length=5)),
                ('organization', models.CharField(default='Not Assigned', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='smart_city_main.User'),
        ),
    ]
