# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='gty_ccn_alert',
            new_name='clean_basin_email_alert',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='gty_sms_alert',
            new_name='clean_basin_web_alert',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='ytr_ccn_alert',
            new_name='gps_update_email_alert',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='ytr_sms_alert',
            new_name='gps_update_web_alert',
        ),
        migrations.AddField(
            model_name='notifications',
            name='gty_web_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='ytr_web_alert',
            field=models.BooleanField(default=False),
        ),
    ]
