# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='gty_ccn_alert',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='gty_sms_alert',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='ytr_ccn_alert',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='ytr_sms_alert',
        ),
        migrations.AddField(
            model_name='notifications',
            name='clean_basin_email_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='clean_basin_web_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='gps_update_email_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='gps_update_web_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='gty_web_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='ytr_web_alert',
            field=models.BooleanField(default=False),
        ),
    ]
