# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillLevelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_level', models.IntegerField(default=0)),
                ('device_identifier', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='smart_city_main.Device')),
            ],
        ),
    ]
