# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0001_initial'),
    ]

    operations = [
    ]
