# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0002_filllevellog'),
    ]

    operations = [
        migrations.AddField(
            model_name='filllevellog',
            name='date_logged',
            field=models.DateTimeField(default=datetime.datetime(1999, 1, 1, 0, 0, 1)),
        ),
    ]
