# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0002_auto_20170928_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=250)),
                ('alert_date', models.DateTimeField()),
                ('device_identifier', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='smart_city_main.Device')),
            ],
        ),
        migrations.AlterField(
            model_name='notifications',
            name='clean_basin_web_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='gps_update_web_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='gty_web_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='ytr_web_alert',
            field=models.BooleanField(default=True),
        ),
    ]
