# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0003_filllevellog_date_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_fill_log_date',
            field=models.DateTimeField(default=datetime.datetime(1999, 1, 1, 0, 0, 1)),
        ),
    ]
