# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0003_auto_20171013_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='waste_type',
            new_name='device_type',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(default='Not Assigned', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(default='User', max_length=5),
        ),
    ]
