# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0003_auto_20171004_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bettery_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='device',
            name='fill_level',
            field=models.IntegerField(default=0),
        ),
    ]
