# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0004_auto_20171015_1459'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='device',
            name='last_notification_date',
            field=models.DateTimeField(default=datetime.datetime(1999, 1, 1, 0, 0, 1)),
        )
    ]
