# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0005_auto_20171101_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='report_interval',
            new_name='sensing_interval',
        ),
    ]
