# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_main', '0005_auto_20171007_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='report_interval',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='gy_thresh',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='yr_thresh',
            field=models.IntegerField(default=60),
        ),
    ]
